# Generated by Django 3.2.8 on 2021-10-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211021_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telephone_number',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
