# Generated by Django 3.2.8 on 2021-10-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone_number',
            field=models.CharField(default='+375', max_length=13),
        ),
    ]
